### ISSUE TITLE
Pl/sql unit test

### ISSUE THREAD

**Issue by carloscasalar** [OraOpenSource/orawrap#10]
Have you planned to create a unit test library on top of orawrap?. I'm thinking in something like [ruby-plsql](https://github.com/rsim/ruby-plsql)  but using mocha.

**Comment by dmcghan** [comment]
@SirRagnar I hadn't even considered it until now! :)

I'm not sure if orawrap would be the right place for this. Maybe something on top of orawrap? Maybe I'm wrong... Could you provide a mockup of how you would use this? How would you integrate orawrap with mocha?
