### ISSUE TITLE
problem when executing method execute with 3 parameters plus then , catch

### ISSUE THREAD

**Issue by pntone** [OraOpenSource/orawrap#11]
The problem in the function 
ConnectionManager.prototype.execute = function(a1, a2, a3, a4) ,  file connectionmanager.js.
Problem exist when executing promise with 3 parameters (sql, binds, opts)  .
Need the same behavior like  case with 2 arguments.

```
            case 3:
                sql = a1;
                bindParams = a2;
```

//                    cb = a3;              // original line 
                   switch (typeof a3) {   // new lines 
                        case 'object':
                            opts = a3;
                            break;
                        case 'function':
                            cb = a3;
                            break;
                    }   // end of new lines 
                    break;

**Comment by dmcghan** [comment]
Thanks for letting me know!

**Comment by dmcghan** [comment]
Fixed in 0.2.2

**Comment by pntone** [comment]
I updated and found a little error  :

```
                switch (typeof a3) {
                    case 'object':
                        bindParams = a3;   // must be opts = a3;
                        break;
                    case 'function':
                        cb = a3;
                        break;
                }
```

**Comment by dmcghan** [comment]
Oppps, thanks! :) 

Should be good now.
