### ISSUE TITLE
Typescript definition file?

### ISSUE THREAD

**Issue by vrmerlin** [OraOpenSource/orawrap#13]
Hi -- great stuff! Just what I needed for my project.

Is there by chance a Typescript definition file created yet? I couldn't find one on TSD.

Thanks,
John

**Comment by dmcghan** [comment]
Hello,

Thanks for your interest. Unfortunately I've not had time to create one. Actually, I'm going to work on getting some of the features in orawrap built into the driver directly (perhaps alleviating the need for orawrap?). But even the driver needs a Typescript definition file... :|

Regards,
Dan

**Comment by vrmerlin** [comment]
Integrating orawrap into the driver sounds great.  Yes,  the driver needs the definition file too :-) thanks for your work on this...  Great stuff.
