### ISSUE TITLE
return json data?

### ISSUE THREAD

**Issue by vrmerlin** [OraOpenSource/orawrap#14]
I'm trying to get up to speed with oracledb and orawrap, and am unclear on something. The execute() results I get back are arrays, without any metadata (column names). Is it possible to get back JSON structures, so I can just pass the results back through a REST interface?

**Comment by dmcghan** [comment]
Answered here: https://github.com/oracle/node-oracledb/issues/265

**Comment by CSester** [comment]
Hi,
With unwrapped oracledb, I'm able to set properties "globally" this way:

``` javascript
oracledb = require(oracledb);
...
oracledb.outFormat = oracledb.OBJECT;
```

And in orawrap you copy some constants

``` javascript
this.OBJECT = oracledb.OBJECT;
```

But, doing this has no effect

``` javascript
orawrap.outFormat = orawrap.OBJECT;
```

Shoud I include oracledb and set the property on the unwrapped object ?

Best regards
