### ISSUE TITLE
Documentation Error: callback parameter order incorrect

### ISSUE THREAD

**Issue by ncorison** [OraOpenSource/orawrap#16]
The documentation indicates that the callback parameters are (err, results) when in fact they are (results, err).

**Comment by dmcghan** [comment]
Hmmm - I hope that's not true ;) Could you share how you came to that conclusion, maybe provide a test case?

**Comment by ncorison** [comment]
Hi Dan,

When I ran this:

var orawrap = require('orawrap');

it('should instantiate the driver', function () {
  var connectData = {
    connectString : localhost:1521/<my_db>',
    user: <user>,
    password: <password>
  };

  orawrap.setConnectInfo(connectData);
});

it('should query for the oracle version', function () {
  orawrap.execute('SELECT \* FROM V$VERSION').then(function(err, results) {
    if (err) { throw err; }
    var oracleVersion = results;
    console.log('Oracle Version: ' + oracleVersion.rows[0][0] + '\n');
  });
});

My results were being returned in variable err and results were null, so I swapped the two:

it('should query for the oracle version', function () {
  orawrap.execute('SELECT \* FROM V$VERSION').then(function(results, err) {
    if (err) { throw err; }
    var oracleVersion = results;
    console.log('Oracle Version: ' + oracleVersion.rows[0][0] + '\n');
  });
});

Oracle Version: Oracle Database 11g Release 11.2.0.4.0 - 64bit Production

and it is working fine now.

Norman Corison
SQA Lead Automation Engineer | Retail Pro International, LLC
Office: + 916-605-7242
E-mail: ncorison@retailpro.com | Web: www.retailpro.com
[cid:image001.gif@01D11B92.3FC40080]

**Comment by dmcghan** [comment]
Ah, I see what happened. You're using the promise API as though it was a callback API. Orawrap supports both, but you have to choose between one or the other.

Here's a callback API example:

``` javascript
it('should query for the oracle version', function () {
  orawrap.execute('SELECT * FROM V$VERSION', function(err, results) {
    if (err) {
      console.error(err);
      return;
    }

    console.log('Oracle Version: ' + results.rows[0][0] + '\n');
  });
});
```

And here's a promise API example:

``` javascript
it('should query for the oracle version', function () {
  orawrap.execute('SELECT * FROM V$VERSION')
    .then(function(results) {
      console.log('Oracle Version: ' + results.rows[0][0] + '\n');
    })
    .catch(function(err) {
      console.error(err);
    }); 
});
```

I hope that helps.

**Comment by ncorison** [comment]
Oh, I see – thanks! I normally would use the callback API, but got so used to using the promise API everywhere in Protractor that my fingers just filled it in!

Norman
