### ISSUE TITLE
Can orawrap support multiple multiple database connections

### ISSUE THREAD

**Issue by ncorison** [OraOpenSource/orawrap#17]
I need to have connections to two databases at the same time (actually the same database with 2 different logins); is that possible?

**Comment by dmcghan** [comment]
You could set the connection info, get a connection, then set the connection info again, and then get another connection. Another option is to use pools. You can create named pools and then use them by name.

**Comment by ncorison** [comment]
Actually, the issue is that the two users access different sets of tables in the same database. From what I can see, these don’t look like they will work for me; please let me know if I’m mistaken.

Thanks!

Norman

**Comment by dmcghan** [comment]
Are the tables in different schemas?

Why would that not work for you?

**Comment by dmcghan** [comment]
Closing due to no response.
