### ISSUE TITLE
reconnections?

### ISSUE THREAD

**Issue by vrmerlin** [OraOpenSource/orawrap#19]
Hi -- Does orawrap support reconnection attempts, if the Oracle database is restarted?

**Comment by dmcghan** [comment]
Sorry for the delayed response. No, it doesn't. Frankly, further development on this project will probably cease as we are exploring options to extend out the driver with a more robust JavaScript layer: https://github.com/oracle/node-oracledb/pull/321 

Perhaps this will make it into the core driver at some point...
