### ISSUE TITLE
Issue with multiple connections

### ISSUE THREAD

**Issue by mrn3** [OraOpenSource/orawrap#20]
I want my node app to connect to multiple Oracle databases.  When I do the code below, the databaseArray[i].connection is the same on both objects in the array and it only queries the second database.  Is there a different way to instantiate orawrap so it will have multiple ones?

var databaseArray = [
  {
    username: <some_username>,
    password: <some_password>,
    hostName: <some_hostname>,
    databaseName: <some_databasename>
  },
  {
    username: <some_username>,
    password: <some_password>,
    hostName: <some_hostname>,
    databaseName: <some_databasename>
  }
]

for (var i=0; i<databaseArray.length; i++) {
  var orawrap = require('orawrap')
  var dbConfig = {
    user: databaseArray[i].userName,
    password: databaseArray[i].password,
    connectString: databaseArray[i].hostName + '/' + databaseArray[i].databaseName
  }
  orawrap.setConnectInfo(dbConfig)
  databaseArray[i].connection = orawrap
}

**Comment by dmcghan** [comment]
The only way to do this right now would be to create multiple connection pools. Just give them different names and you should be all set.
