### ISSUE TITLE
Expose Oracledb properties

### ISSUE THREAD

**Issue by ghost** [OraOpenSource/orawrap#21]
As far as I understand there doesn't seem to be a direct way to set the global Oracledb properties via orawrap. For example, in order to set the 'fetchAsString' property you need to include the oracledb module and do:

`require('oracledb').fetchAsString = [oracledb.DATE];`

Maybe it would be better to expose these properties through orawrap so you could write something like:

`orawrap.fetchAsString = [orawrap.DATE];`
 or
`orawrap.db.fetchAsString = [orawrap.DATE];`
or
`orawrap.setProperty('fetchAsString', [orawrap.DATE])`

**Comment by dmcghan** [comment]
@Laphro Thanks for logging an issue. For a variety of reasons I will not be continuing to work on Orawrap. However, we are working on incorporating many of the features of Orawrap directly in the driver. Stay tuned! :)
