### ISSUE TITLE
How to query CLOB Data Type Values?

### ISSUE THREAD

**Issue by talasila66** [OraOpenSource/orawrap#27]
How to query CLOB Data Type Values as String?

Tried this way 

var options={
sql: select deatils from ads,
bindprams:{},
 fetchAsString: [orawrap.CLOB]
};

 orawrap.execute(options.sql, options.bindParams, options.opts, function(err, results) {
            callback(err, results);
        });

**Comment by dmcghan** [comment]
@talasila66 Orawrap is no longer being actively developed. Please use the base driver instead.

**Comment by talasila66** [comment]
@dmcghan can you please help me by pointing to base driver package?

**Comment by dmcghan** [comment]
@talasila66  It's at http://github.com/oracle/node-oracledb

**Comment by talasila66** [comment]
@dmcghan Can we get the connection pool features in base driver package also?

**Comment by dmcghan** [comment]
@talasila66 We've migrated all of the features of Orawrap to the base driver save one: simple execute. We are still reviewing this one internally.
