### ISSUE TITLE
Pool manager leaks async workers on failed buildup scripts

### ISSUE THREAD

**Issue by michaelabuckley** [OraOpenSource/orawrap#8]
If a buildup script generates an error, the async.eachSeries error handler never calls the async worker releaseCb.  This leaks a pool worker, and causes eventual exhaustion.

Bug also applies to v0.1.0

I've sent a pull-request with a fix for head.

**Comment by dmcghan** [comment]
@michaelabuckley Thanks for the PR. Will address soon... I wanted to run something by you since you are using the buildup scripts. Currently there are 2 timings: get connection and release connection. These are addressed via the addBuildupSql and addTeardown methods respectively. 

What would you think about having just 1 method: addStatement 

There would be 4 different timings instead of 2:
postGetConnection: replaces addBuildupSql
preReleaseConnection: replaces addTeardownSql
preExecute: new
postExecute: new

The timing could be a separate parameter to addStatement:

``` javascript
orawrap.addStatement('postGetConnection', {
  sql: "begin execute immediate q'[alter session set NLS_DATE_FORMAT='DD-MM-YYYY']'; end;"
});
```

Or the timing could just be an additional property on the statement object:

``` javascript
orawrap.addStatement({
  timing: "postGetConnection",
  sql: "begin execute immediate q'[alter session set NLS_DATE_FORMAT='DD-MM-YYYY']'; end;"
});
```

I'm leaning toward the latter.

The addStatement method would be available on the base class (orawrap) but also on each pool instance. By default, statements added via the base class would only apply to connections that are NOT obtained from pools. Of course we could add a separate property to make them apply to all pools too:

``` javascript
orawrap.addStatement({
  timing: "postGetConnection",
  allPools: true, //defaults to false
  sql: "begin execute immediate q'[alter session set NLS_DATE_FORMAT='DD-MM-YYYY']'; end;"
});
```

Finally, if addStatement was called on a pool class the statements would only apply to connections in that pool.

What do you think?

**Comment by dmcghan** [comment]
Of course, now that I've said all that, I think I would change addStatement to addConnectionSql and drop "connection" from the timings. So...

method: 
addConnectionSql

timings:
postGet
preRelease
preExecute
postExecute

**Comment by michaelabuckley** [comment]
I don’t have a need for these, so I don’t have much of an opinion.

One thing I could use is a proper health check with retry.  Currently I have a retry loop outside in my express middleware for when a buildupSql script fails.  This is helpful for when the connection has gone stale (dropped connection, killed on  server, etc.).  E.g.

   doIt();

```
function doIt() {
  activeConfig.getConnection()
    .then(withConnection, openErrorHandler);
}

function openErrorHandler(error) {
  var delay;
    if (error.message &&
        (error.message.startsWith('ORA-24418') || error.message.startsWith('ORA-04068')) &&
        retries < maxRetries) {
    retries = retries + 1;
      logger.error('Retrying db connection: ', retries, error);
    setTimeout(doIt);
    return;
  }
    logger.error('Failed to open connection: ', error);
  next(error);
}
```

It’s a pretty common use for pre-scripts.

Michael

**Comment by dmcghan** [comment]
@michaelabuckley Just so you know, you shouldn't be getting the ORA-24418 errors since connection request queuing was added. Have you tested that?

As for the ORA-04068, you should be able to fix that with:

``` javascript
orawrap.addTeardownSql({
  sql: "begin sys.dbms_session.modify_package_state(sys.dbms_session.reinitialize); end;"
});
```

Could you please verify if these changes fix your issues?

Regards,
Dan

**Comment by michaelabuckley** [comment]
You’re right on the ORA-24418 errors.  That was fixed with your queue workers (a happy surprise).

But the general problem of checking for a bad connection stands.  I’m usually apply a health check before pulling a connection out of the pool.  It could be bad for all sorts of reasons.

Michael

**Comment by dmcghan** [comment]
@michaelabuckley Okay, we can explore this issue some more. But first, can you please confirm if the dbms_session call addressed your ORA-04068 issue?

**Comment by michaelabuckley** [comment]
I haven’t had it for a while, so yes.

**Comment by michaelabuckley** [comment]
My biggest problem is ORA-01426.  I haven’t hit in production yet, but in dev, sometimes the driver goes bad and any PLSQL NUMBER out param blows up with ORA-01426.

Have you seen this?

Thanks,
Michael

**Comment by dmcghan** [comment]
@michaelabuckley No, I've not seen that. I ran some tests trying to reproduce but I wasn't able to. Can you provide more details? Was the driver not used for a while and then, when used, this happened? Can you show me your pool config settings?

**Comment by michaelabuckley** [comment]
Nothing exotic.  

  poolMax : 2,

 config.poolName = 'twig';
   orawrap.addBuildupSql({ sql : 'begin d(VAULT_API.date_fmt(sysdate)); end;' });
  orawrap.addTeardownSql({sql: "BEGIN \
if (dbms_transaction.local_transaction_id is not null) then \
   ROLLBACK; RAISE_APPLICATION_ERROR(-20000,'Session has open transaction on return to pool'); \
end if; END;"});
  orawrap.addTeardownSql({sql:'BEGIN ROLLBACK;END;'});
  orawrap.createPool(config);

I do have some weird local network issues.

**Comment by dmcghan** [comment]
What about your poolMin and your poolTimeout?

**Comment by michaelabuckley** [comment]
Not set.

**Comment by dmcghan** [comment]
@michaelabuckley This is a tough one. The error you're getting isn't related to getting a connection. So your request to add a connection health check wouldn't really help in this case. I just can't think of a good way to do this.

Something else... I noticed in your code that you have 2 addTeardownSql statements with rollbacks. The second seems superfluous, no? Check out this section in the documentation on transaction management (you shouln't have to do rollbacks as they are the default): https://github.com/oracle/node-oracledb/blob/master/doc/api.md#transactionmgt

**Comment by michaelabuckley** [comment]
Thanks.  That was left over.  The more important call was 
    if (dbms_transaction.local_transaction_id is not null) then
That is there to catch my application bugs.  I had some paths failing to commit, and that teardown was find them.

**Comment by dmcghan** [comment]
The default value of autoCommit is false, so it should be rolling back for you unless someone sets autoCommit to true.

Thanks for your help!
